// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "operator_mul.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic operator_mul::ap_const_logic_1 = sc_dt::Log_1;
const bool operator_mul::ap_const_boolean_1 = true;
const bool operator_mul::ap_const_boolean_0 = false;
const sc_lv<32> operator_mul::ap_const_lv32_80 = "10000000";
const sc_lv<32> operator_mul::ap_const_lv32_9F = "10011111";
const sc_lv<32> operator_mul::ap_const_lv32_100 = "100000000";
const sc_lv<32> operator_mul::ap_const_lv32_11F = "100011111";
const sc_lv<32> operator_mul::ap_const_lv32_180 = "110000000";
const sc_lv<32> operator_mul::ap_const_lv32_19F = "110011111";
const sc_lv<32> operator_mul::ap_const_lv32_20 = "100000";
const sc_lv<32> operator_mul::ap_const_lv32_3F = "111111";
const sc_lv<32> operator_mul::ap_const_lv32_A0 = "10100000";
const sc_lv<32> operator_mul::ap_const_lv32_BF = "10111111";
const sc_lv<32> operator_mul::ap_const_lv32_120 = "100100000";
const sc_lv<32> operator_mul::ap_const_lv32_13F = "100111111";
const sc_lv<32> operator_mul::ap_const_lv32_1A0 = "110100000";
const sc_lv<32> operator_mul::ap_const_lv32_1BF = "110111111";
const sc_lv<32> operator_mul::ap_const_lv32_40 = "1000000";
const sc_lv<32> operator_mul::ap_const_lv32_5F = "1011111";
const sc_lv<32> operator_mul::ap_const_lv32_C0 = "11000000";
const sc_lv<32> operator_mul::ap_const_lv32_DF = "11011111";
const sc_lv<32> operator_mul::ap_const_lv32_140 = "101000000";
const sc_lv<32> operator_mul::ap_const_lv32_15F = "101011111";
const sc_lv<32> operator_mul::ap_const_lv32_1C0 = "111000000";
const sc_lv<32> operator_mul::ap_const_lv32_1DF = "111011111";
const sc_logic operator_mul::ap_const_logic_0 = sc_dt::Log_0;

operator_mul::operator_mul(sc_module_name name) : sc_module(name), mVcdFile(0) {
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1->din0(tmp_i_reg_435);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1->din1(tmp_i_15_reg_440);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1->dout(grp_fu_84_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2->din0(tmp_20_i_reg_445);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2->din1(grp_fu_88_p1);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2->dout(grp_fu_88_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3->din0(tmp_i4_reg_450);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3->din1(tmp_i5_reg_455);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3->dout(grp_fu_92_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4->din0(tmp_20_i7_reg_460);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4->din1(grp_fu_96_p1);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4->dout(grp_fu_96_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5->din0(tmp_i1_reg_465);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5->din1(tmp_i1_16_reg_470);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5->dout(grp_fu_100_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6->din0(tmp_20_i1_reg_475);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6->din1(grp_fu_104_p1);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6->dout(grp_fu_104_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7->din0(tmp1_reg_500);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7->din1(tmp_reg_495);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7->dout(grp_fu_108_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8->din0(tmp3_reg_510);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8->din1(tmp2_reg_505);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8->dout(grp_fu_112_p2);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9 = new integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9");
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9->clk(ap_clk);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9->reset(ap_rst);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9->din0(tmp5_reg_520);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9->din1(tmp4_reg_515);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9->ce(ap_var_for_const0);
    integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9->dout(grp_fu_116_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10->din0(grp_fu_120_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10->din1(v_x_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10->dout(grp_fu_120_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11->din0(grp_fu_125_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11->din1(v_y_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11->dout(grp_fu_125_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12->din0(grp_fu_130_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12->din1(v_z_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12->dout(grp_fu_130_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13->din0(grp_fu_135_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13->din1(v_x_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13->dout(grp_fu_135_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14->din0(grp_fu_140_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14->din1(v_y_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14->dout(grp_fu_140_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15->din0(grp_fu_145_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15->din1(v_z_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15->dout(grp_fu_145_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16->din0(grp_fu_150_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16->din1(v_x_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16->dout(grp_fu_150_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17->din0(grp_fu_155_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17->din1(v_y_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17->dout(grp_fu_155_p2);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18 = new integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>("integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18");
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18->clk(ap_clk);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18->reset(ap_rst);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18->din0(grp_fu_160_p0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18->din1(v_z_read_int_reg);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18->ce(ap_var_for_const0);
    integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18->dout(grp_fu_160_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_fu_108_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_fu_112_p2 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_fu_116_p2 );

    SC_METHOD(thread_grp_fu_104_p1);
    sensitive << ( tmp_13_reg_430_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_120_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_6_fu_165_p1 );

    SC_METHOD(thread_grp_fu_125_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_8_fu_174_p4 );

    SC_METHOD(thread_grp_fu_130_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_s_fu_189_p4 );

    SC_METHOD(thread_grp_fu_135_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_9_fu_214_p4 );

    SC_METHOD(thread_grp_fu_140_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_1_fu_229_p4 );

    SC_METHOD(thread_grp_fu_145_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_fu_244_p4 );

    SC_METHOD(thread_grp_fu_150_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_10_fu_269_p4 );

    SC_METHOD(thread_grp_fu_155_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_11_fu_284_p4 );

    SC_METHOD(thread_grp_fu_160_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_12_fu_299_p4 );

    SC_METHOD(thread_grp_fu_88_p1);
    sensitive << ( tmp_4_reg_390_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_96_p1);
    sensitive << ( tmp_3_reg_410_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_10_fu_269_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_11_fu_284_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_12_fu_299_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_1_fu_229_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_2_fu_244_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_6_fu_165_p1);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_8_fu_174_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_9_fu_214_p4);
    sensitive << ( M_data_read_int_reg );

    SC_METHOD(thread_tmp_s_fu_189_p4);
    sensitive << ( M_data_read_int_reg );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "operator_mul_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, M_data_read, "(port)M_data_read");
    sc_trace(mVcdFile, v_x_read, "(port)v_x_read");
    sc_trace(mVcdFile, v_y_read, "(port)v_y_read");
    sc_trace(mVcdFile, v_z_read, "(port)v_z_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, tmp_4_reg_390, "tmp_4_reg_390");
    sc_trace(mVcdFile, tmp_4_reg_390_pp0_iter1_reg, "tmp_4_reg_390_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_3_reg_410, "tmp_3_reg_410");
    sc_trace(mVcdFile, tmp_3_reg_410_pp0_iter1_reg, "tmp_3_reg_410_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_13_reg_430, "tmp_13_reg_430");
    sc_trace(mVcdFile, tmp_13_reg_430_pp0_iter1_reg, "tmp_13_reg_430_pp0_iter1_reg");
    sc_trace(mVcdFile, grp_fu_120_p2, "grp_fu_120_p2");
    sc_trace(mVcdFile, tmp_i_reg_435, "tmp_i_reg_435");
    sc_trace(mVcdFile, grp_fu_125_p2, "grp_fu_125_p2");
    sc_trace(mVcdFile, tmp_i_15_reg_440, "tmp_i_15_reg_440");
    sc_trace(mVcdFile, grp_fu_130_p2, "grp_fu_130_p2");
    sc_trace(mVcdFile, tmp_20_i_reg_445, "tmp_20_i_reg_445");
    sc_trace(mVcdFile, grp_fu_135_p2, "grp_fu_135_p2");
    sc_trace(mVcdFile, tmp_i4_reg_450, "tmp_i4_reg_450");
    sc_trace(mVcdFile, grp_fu_140_p2, "grp_fu_140_p2");
    sc_trace(mVcdFile, tmp_i5_reg_455, "tmp_i5_reg_455");
    sc_trace(mVcdFile, grp_fu_145_p2, "grp_fu_145_p2");
    sc_trace(mVcdFile, tmp_20_i7_reg_460, "tmp_20_i7_reg_460");
    sc_trace(mVcdFile, grp_fu_150_p2, "grp_fu_150_p2");
    sc_trace(mVcdFile, tmp_i1_reg_465, "tmp_i1_reg_465");
    sc_trace(mVcdFile, grp_fu_155_p2, "grp_fu_155_p2");
    sc_trace(mVcdFile, tmp_i1_16_reg_470, "tmp_i1_16_reg_470");
    sc_trace(mVcdFile, grp_fu_160_p2, "grp_fu_160_p2");
    sc_trace(mVcdFile, tmp_20_i1_reg_475, "tmp_20_i1_reg_475");
    sc_trace(mVcdFile, grp_fu_84_p2, "grp_fu_84_p2");
    sc_trace(mVcdFile, tmp_reg_495, "tmp_reg_495");
    sc_trace(mVcdFile, grp_fu_88_p2, "grp_fu_88_p2");
    sc_trace(mVcdFile, tmp1_reg_500, "tmp1_reg_500");
    sc_trace(mVcdFile, grp_fu_92_p2, "grp_fu_92_p2");
    sc_trace(mVcdFile, tmp2_reg_505, "tmp2_reg_505");
    sc_trace(mVcdFile, grp_fu_96_p2, "grp_fu_96_p2");
    sc_trace(mVcdFile, tmp3_reg_510, "tmp3_reg_510");
    sc_trace(mVcdFile, grp_fu_100_p2, "grp_fu_100_p2");
    sc_trace(mVcdFile, tmp4_reg_515, "tmp4_reg_515");
    sc_trace(mVcdFile, grp_fu_104_p2, "grp_fu_104_p2");
    sc_trace(mVcdFile, tmp5_reg_520, "tmp5_reg_520");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, grp_fu_88_p1, "grp_fu_88_p1");
    sc_trace(mVcdFile, grp_fu_96_p1, "grp_fu_96_p1");
    sc_trace(mVcdFile, grp_fu_104_p1, "grp_fu_104_p1");
    sc_trace(mVcdFile, grp_fu_120_p0, "grp_fu_120_p0");
    sc_trace(mVcdFile, grp_fu_125_p0, "grp_fu_125_p0");
    sc_trace(mVcdFile, grp_fu_130_p0, "grp_fu_130_p0");
    sc_trace(mVcdFile, grp_fu_135_p0, "grp_fu_135_p0");
    sc_trace(mVcdFile, grp_fu_140_p0, "grp_fu_140_p0");
    sc_trace(mVcdFile, grp_fu_145_p0, "grp_fu_145_p0");
    sc_trace(mVcdFile, grp_fu_150_p0, "grp_fu_150_p0");
    sc_trace(mVcdFile, grp_fu_155_p0, "grp_fu_155_p0");
    sc_trace(mVcdFile, grp_fu_160_p0, "grp_fu_160_p0");
    sc_trace(mVcdFile, tmp_6_fu_165_p1, "tmp_6_fu_165_p1");
    sc_trace(mVcdFile, tmp_8_fu_174_p4, "tmp_8_fu_174_p4");
    sc_trace(mVcdFile, tmp_s_fu_189_p4, "tmp_s_fu_189_p4");
    sc_trace(mVcdFile, tmp_9_fu_214_p4, "tmp_9_fu_214_p4");
    sc_trace(mVcdFile, tmp_1_fu_229_p4, "tmp_1_fu_229_p4");
    sc_trace(mVcdFile, tmp_2_fu_244_p4, "tmp_2_fu_244_p4");
    sc_trace(mVcdFile, tmp_10_fu_269_p4, "tmp_10_fu_269_p4");
    sc_trace(mVcdFile, tmp_11_fu_284_p4, "tmp_11_fu_284_p4");
    sc_trace(mVcdFile, tmp_12_fu_299_p4, "tmp_12_fu_299_p4");
    sc_trace(mVcdFile, grp_fu_108_p2, "grp_fu_108_p2");
    sc_trace(mVcdFile, grp_fu_112_p2, "grp_fu_112_p2");
    sc_trace(mVcdFile, grp_fu_116_p2, "grp_fu_116_p2");
    sc_trace(mVcdFile, M_data_read_int_reg, "M_data_read_int_reg");
    sc_trace(mVcdFile, v_x_read_int_reg, "v_x_read_int_reg");
    sc_trace(mVcdFile, v_y_read_int_reg, "v_y_read_int_reg");
    sc_trace(mVcdFile, v_z_read_int_reg, "v_z_read_int_reg");
#endif

    }
}

operator_mul::~operator_mul() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U1;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U2;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U3;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U4;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U5;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U6;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U7;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U8;
    delete integrateKernel_fadd_32ns_32ns_32_4_full_dsp_1_U9;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U10;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U11;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U12;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U13;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U14;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U15;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U16;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U17;
    delete integrateKernel_fmul_32ns_32ns_32_2_max_dsp_1_U18;
}

void operator_mul::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void operator_mul::thread_ap_clk_no_reset_() {
    M_data_read_int_reg = M_data_read.read();
    v_x_read_int_reg = v_x_read.read();
    v_y_read_int_reg = v_y_read.read();
    v_z_read_int_reg = v_z_read.read();
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        tmp1_reg_500 = grp_fu_88_p2.read();
        tmp2_reg_505 = grp_fu_92_p2.read();
        tmp3_reg_510 = grp_fu_96_p2.read();
        tmp4_reg_515 = grp_fu_100_p2.read();
        tmp5_reg_520 = grp_fu_104_p2.read();
        tmp_13_reg_430 = M_data_read_int_reg.read().range(479, 448);
        tmp_13_reg_430_pp0_iter1_reg = tmp_13_reg_430.read();
        tmp_20_i1_reg_475 = grp_fu_160_p2.read();
        tmp_20_i7_reg_460 = grp_fu_145_p2.read();
        tmp_20_i_reg_445 = grp_fu_130_p2.read();
        tmp_3_reg_410 = M_data_read_int_reg.read().range(447, 416);
        tmp_3_reg_410_pp0_iter1_reg = tmp_3_reg_410.read();
        tmp_4_reg_390 = M_data_read_int_reg.read().range(415, 384);
        tmp_4_reg_390_pp0_iter1_reg = tmp_4_reg_390.read();
        tmp_i1_16_reg_470 = grp_fu_155_p2.read();
        tmp_i1_reg_465 = grp_fu_150_p2.read();
        tmp_i4_reg_450 = grp_fu_135_p2.read();
        tmp_i5_reg_455 = grp_fu_140_p2.read();
        tmp_i_15_reg_440 = grp_fu_125_p2.read();
        tmp_i_reg_435 = grp_fu_120_p2.read();
        tmp_reg_495 = grp_fu_84_p2.read();
    }
}

void operator_mul::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void operator_mul::thread_ap_return_0() {
    ap_return_0 = grp_fu_108_p2.read();
}

void operator_mul::thread_ap_return_1() {
    ap_return_1 = grp_fu_112_p2.read();
}

void operator_mul::thread_ap_return_2() {
    ap_return_2 = grp_fu_116_p2.read();
}

void operator_mul::thread_grp_fu_104_p1() {
    grp_fu_104_p1 = tmp_13_reg_430_pp0_iter1_reg.read();
}

void operator_mul::thread_grp_fu_120_p0() {
    grp_fu_120_p0 = tmp_6_fu_165_p1.read();
}

void operator_mul::thread_grp_fu_125_p0() {
    grp_fu_125_p0 = tmp_8_fu_174_p4.read();
}

void operator_mul::thread_grp_fu_130_p0() {
    grp_fu_130_p0 = tmp_s_fu_189_p4.read();
}

void operator_mul::thread_grp_fu_135_p0() {
    grp_fu_135_p0 = tmp_9_fu_214_p4.read();
}

void operator_mul::thread_grp_fu_140_p0() {
    grp_fu_140_p0 = tmp_1_fu_229_p4.read();
}

void operator_mul::thread_grp_fu_145_p0() {
    grp_fu_145_p0 = tmp_2_fu_244_p4.read();
}

void operator_mul::thread_grp_fu_150_p0() {
    grp_fu_150_p0 = tmp_10_fu_269_p4.read();
}

void operator_mul::thread_grp_fu_155_p0() {
    grp_fu_155_p0 = tmp_11_fu_284_p4.read();
}

void operator_mul::thread_grp_fu_160_p0() {
    grp_fu_160_p0 = tmp_12_fu_299_p4.read();
}

void operator_mul::thread_grp_fu_88_p1() {
    grp_fu_88_p1 = tmp_4_reg_390_pp0_iter1_reg.read();
}

void operator_mul::thread_grp_fu_96_p1() {
    grp_fu_96_p1 = tmp_3_reg_410_pp0_iter1_reg.read();
}

void operator_mul::thread_tmp_10_fu_269_p4() {
    tmp_10_fu_269_p4 = M_data_read_int_reg.read().range(95, 64);
}

void operator_mul::thread_tmp_11_fu_284_p4() {
    tmp_11_fu_284_p4 = M_data_read_int_reg.read().range(223, 192);
}

void operator_mul::thread_tmp_12_fu_299_p4() {
    tmp_12_fu_299_p4 = M_data_read_int_reg.read().range(351, 320);
}

void operator_mul::thread_tmp_1_fu_229_p4() {
    tmp_1_fu_229_p4 = M_data_read_int_reg.read().range(191, 160);
}

void operator_mul::thread_tmp_2_fu_244_p4() {
    tmp_2_fu_244_p4 = M_data_read_int_reg.read().range(319, 288);
}

void operator_mul::thread_tmp_6_fu_165_p1() {
    tmp_6_fu_165_p1 = M_data_read_int_reg.read().range(32-1, 0);
}

void operator_mul::thread_tmp_8_fu_174_p4() {
    tmp_8_fu_174_p4 = M_data_read_int_reg.read().range(159, 128);
}

void operator_mul::thread_tmp_9_fu_214_p4() {
    tmp_9_fu_214_p4 = M_data_read_int_reg.read().range(63, 32);
}

void operator_mul::thread_tmp_s_fu_189_p4() {
    tmp_s_fu_189_p4 = M_data_read_int_reg.read().range(287, 256);
}

}

